# Generated by Django 5.0.7 on 2024-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
